"""descrição das mudanças

Revision ID: 6f4957597037
Revises: 30bb486a8aea
Create Date: 2025-07-31 07:01:37.951378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f4957597037'
down_revision: Union[str, Sequence[str], None] = '30bb486a8aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RPAProposalV2')
    op.drop_table('RPAProposal')
    op.drop_table('Event')
    op.drop_table('Employee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Employee_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Employee_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('RPAProposalV2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('integration_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], name=op.f('RPAProposalV2_employee_id_fkey')),
    sa.ForeignKeyConstraint(['event_id'], ['Event.id'], name=op.f('RPAProposalV2_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('RPAProposalV2_pkey'))
    )
    op.create_table('Event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Event_pkey'))
    )
    op.create_table('RPAProposal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employeeId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('eventId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('integrationDateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('RPAProposal_pkey'))
    )
    # ### end Alembic commands ###
